#include "dashcam_redactor/cli.hpp"
#include "dashcam_redactor/error.hpp"
#include "dashcam_redactor/video_io.hpp"

#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>

#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <random>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <utility>
#include <vector>

namespace {
namespace fs = std::filesystem;
namespace dr = dashcam_redactor;
constexpr int fixture_frames = 12;
constexpr double fixture_fps = 12.5;
const cv::Size fixture_size(64, 48);

void require(bool condition, std::string_view message) {
    if (!condition) {
        throw std::runtime_error(std::string(message));
    }
}

template <typename Function>
void expect_error(dr::ExitCode code, Function function) {
    try {
        function();
    } catch (const dr::Error& error) {
        require(error.code() == code, "Wrong error category");
        require(std::string_view(error.what()).size() > 0, "Empty error message");
        return;
    }
    throw std::runtime_error("Expected an error");
}

void generate_fixture(const fs::path& path) {
    std::error_code error;
    const auto status = fs::symlink_status(path, error);
    if (error && error != std::errc::no_such_file_or_directory) {
        throw dr::Error(dr::ExitCode::output, "Cannot inspect fixture output path: " + error.message());
    }
    if (fs::exists(status)) {
        throw dr::Error(dr::ExitCode::output,
                        "Fixture output already exists; refusing to overwrite it.");
    }
    const int codec = path.extension() == ".mov" ? cv::VideoWriter::fourcc('m', 'p', '4', 'v')
                                               : cv::VideoWriter::fourcc('M', 'J', 'P', 'G');
    cv::VideoWriter writer(path.string(), cv::CAP_FFMPEG, codec, fixture_fps, fixture_size);
    require(writer.isOpened(), "Synthetic fixture encoder unavailable (FFmpeg/MJPG/mp4v required)");
    for (int index = 0; index < fixture_frames; ++index) {
        // Distinct colors and a moving block make frame loss/reordering observable.
        cv::Mat frame(fixture_size, CV_8UC3, cv::Scalar(index * 15, 180 - index * 10, 40 + index * 12));
        frame(cv::Rect(index * 4, 8, 12, 12)).setTo(cv::Scalar(240, 240, 240));
        writer.write(frame);
    }
    writer.release();
}

std::string read_bytes(const fs::path& path) {
    std::ifstream file(path, std::ios::binary);
    require(file.is_open(), "Cannot read fixture bytes");
    return {std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>()};
}

void verify_pair(const fs::path& input, const fs::path& output) {
    cv::VideoCapture source(input.string(), cv::CAP_FFMPEG);
    cv::VideoCapture result(output.string(), cv::CAP_FFMPEG);
    require(source.isOpened() && result.isOpened(), "Cannot reopen fixture/output");
    require(std::abs(source.get(cv::CAP_PROP_FPS) - result.get(cv::CAP_PROP_FPS)) < 0.01,
            "Frame rate not preserved");
    cv::Mat before;
    cv::Mat after;
    int count = 0;
    while (source.read(before)) {
        require(result.read(after), "Output lost a frame");
        require(before.size() == after.size(), "Frame dimensions not preserved");
        require(cv::norm(before, after, cv::NORM_L1) / static_cast<double>(before.total() * 3) < 10,
                "Frames changed excessively or were reordered");
        ++count;
    }
    require(!result.read(after), "Output gained a frame");
    require(count == fixture_frames, "Unexpected fixture frame count");
}

class TestDirectory {
public:
    TestDirectory() {
        std::random_device random;
        for (int attempt = 0; attempt < 32; ++attempt) {
            path = fs::current_path() / (".dashcam-redactor-tests-" + std::to_string(random()));
            if (fs::create_directory(path)) {
                return;
            }
        }
        throw std::runtime_error("Cannot reserve test directory");
    }
    ~TestDirectory() {
        // All contents are generated by this test under its reserved directory.
        std::error_code error;
        fs::remove_all(path, error);
        if (error) {
            std::cerr << "Test fixture cleanup failed: " << error.message() << '\n';
        }
    }
    fs::path path;
};

class DestinationRaceBuffer : public std::stringbuf {
public:
    explicit DestinationRaceBuffer(fs::path destination, bool directory = false)
        : destination_(std::move(destination)), directory_(directory) {}

protected:
    std::streamsize xsputn(const char* text, std::streamsize count) override {
        if (std::string_view(text, static_cast<std::size_t>(count)).find("Verifying encoded output") !=
            std::string_view::npos) {
            if (directory_) {
                fs::create_directory(destination_);
            } else {
                std::ofstream(destination_) << "Created during encoding; preserve me";
            }
        }
        return std::stringbuf::xsputn(text, count);
    }

private:
    fs::path destination_;
    bool directory_;
};

class VerificationFailureBuffer : public std::stringbuf {
public:
    explicit VerificationFailureBuffer(fs::path parent) : parent_(std::move(parent)) {}

protected:
    std::streamsize xsputn(const char* text, std::streamsize count) override {
        if (std::string_view(text, static_cast<std::size_t>(count)).find("Verifying encoded output") !=
            std::string_view::npos) {
            // The writer has closed. Corrupt only this test's owned staged file
            // to exercise failed verification without depending on a codec bug.
            for (const auto& entry : fs::directory_iterator(parent_)) {
                if (entry.is_directory() &&
                    entry.path().filename().string().starts_with(".dashcam-redactor-")) {
                    fs::resize_file(entry.path() / "video.mp4", 0);
                }
            }
        }
        return std::stringbuf::xsputn(text, count);
    }

private:
    fs::path parent_;
};

void parser_tests() {
    const std::vector<std::string_view> valid = {"clip with spaces.mov", "--output", "out.mp4"};
    const auto options = dr::parse_arguments(valid);
    require(options.input == "clip with spaces.mov" && options.output == "out.mp4" && !options.help,
            "Valid arguments parsed incorrectly");
    const std::vector<std::string_view> reordered = {"--output", "out.avi", "input.mov"};
    require(dr::parse_arguments(reordered).input == "input.mov", "Output-first arguments failed");
    const std::vector<std::string_view> escaped = {"--output", "out.mp4", "--", "-input.mov"};
    require(dr::parse_arguments(escaped).input == "-input.mov", "Positional separator failed");
    for (const auto help : {"--help", "-h"}) {
        const std::vector<std::string_view> arguments = {help};
        require(dr::parse_arguments(arguments).help, "Help did not parse");
    }
    const std::vector<std::vector<std::string_view>> invalid = {
        {}, {"input.mov"}, {"--output", "out.mp4"}, {"input.mov", "--output"},
        {"input.mov", "--output", "--help"}, {"input.mov", "--output", ""},
        {"input.mov", "--unknown", "--output", "out.mp4"},
        {"one.mov", "two.mov", "--output", "out.mp4"},
        {"input.mov", "--output", "a.mp4", "--output", "b.mp4"},
        {"--help", "input.mov"}, {"", "--output", "out.mp4"}};
    for (const auto& arguments : invalid) {
        expect_error(dr::ExitCode::usage, [&] { (void)dr::parse_arguments(arguments); });
    }
}

void video_tests() {
    TestDirectory directory;
    const auto input = directory.path / "synthetic input.avi";
    generate_fixture(input);
    const auto original_bytes = read_bytes(input);
    expect_error(dr::ExitCode::output, [&] { generate_fixture(input); });
    require(read_bytes(input) == original_bytes, "Fixture generator changed an existing video");
    const auto existing_fixture = directory.path / "existing fixture.avi";
    std::ofstream(existing_fixture) << "Keep these original bytes";
    expect_error(dr::ExitCode::output, [&] { generate_fixture(existing_fixture); });
    require(read_bytes(existing_fixture) == "Keep these original bytes",
            "Fixture generator overwrote an existing non-video file");
    expect_error(dr::ExitCode::output, [&] { generate_fixture(directory.path); });
    std::ostringstream progress;
    int result_index = 0;
    for (const auto extension : {".avi", ".mp4", ".MP4"}) {
        const auto output = directory.path / ("result" + std::to_string(result_index++) + extension);
        const auto report = dr::transcode_video(input, output, progress);
        require(report.frames == fixture_frames && report.width == fixture_size.width &&
                    report.height == fixture_size.height && std::abs(report.fps - fixture_fps) < 0.01,
                "Processing report is incorrect");
        verify_pair(input, output);
        const auto published_bytes = read_bytes(output);
        expect_error(dr::ExitCode::output,
                     [&] { (void)dr::transcode_video(input, output, progress); });
        require(read_bytes(output) == published_bytes, "Existing output bytes were changed");
        verify_pair(input, output);
    }
    const auto mov_input = directory.path / "synthetic.mov";
    const auto mov_output = directory.path / "mov result.mp4";
    generate_fixture(mov_input);
    const auto mov_report = dr::transcode_video(mov_input, mov_output, progress);
    require(mov_report.frames == fixture_frames, "MOV round trip lost frames");
    verify_pair(mov_input, mov_output);

    const auto race_output = directory.path / "raced.mp4";
    DestinationRaceBuffer race_buffer(race_output);
    std::ostream race_progress(&race_buffer);
    expect_error(dr::ExitCode::output,
                 [&] { (void)dr::transcode_video(input, race_output, race_progress); });
    require(read_bytes(race_output) == "Created during encoding; preserve me",
            "A destination created during encoding was overwritten");

    const auto race_directory = directory.path / "raced directory.mp4";
    DestinationRaceBuffer directory_race_buffer(race_directory, true);
    std::ostream directory_race_progress(&directory_race_buffer);
    expect_error(dr::ExitCode::output,
                 [&] { (void)dr::transcode_video(input, race_directory, directory_race_progress); });
    require(fs::is_directory(race_directory) && fs::is_empty(race_directory),
            "A destination directory created during encoding was changed");
    fs::remove(race_directory);

    const auto failed_verification = directory.path / "failed verification.mp4";
    VerificationFailureBuffer failure_buffer(directory.path);
    std::ostream failure_progress(&failure_buffer);
    expect_error(dr::ExitCode::processing,
                 [&] { (void)dr::transcode_video(input, failed_verification, failure_progress); });
    require(!fs::exists(failed_verification), "Failed verification published an output");

    const auto symlink_output = directory.path / "dangling.mp4";
    std::error_code symlink_error;
    fs::create_symlink(directory.path / "absent-target.mp4", symlink_output, symlink_error);
    if (!symlink_error) {
        expect_error(dr::ExitCode::output, [&] { generate_fixture(symlink_output); });
        require(!fs::exists(directory.path / "absent-target.mp4"),
                "Fixture generator wrote through a dangling symlink");
        expect_error(dr::ExitCode::output,
                     [&] { (void)dr::transcode_video(input, symlink_output, progress); });
        require(fs::is_symlink(symlink_output), "Existing dangling symlink was changed");
    } else {
        std::cout << "Symlink test skipped: local symlink creation is unavailable.\n";
    }
    expect_error(dr::ExitCode::input, [&] {
        (void)dr::transcode_video(directory.path / "missing.mov", directory.path / "missing.mp4", progress);
    });
    expect_error(dr::ExitCode::input, [&] {
        (void)dr::transcode_video(directory.path, directory.path / "directory.mp4", progress);
    });
    const auto invalid = directory.path / "invalid.mov";
    std::ofstream(invalid) << "This is synthetic text, not video.\n";
    const auto invalid_output = directory.path / "invalid.mp4";
    expect_error(dr::ExitCode::input,
                 [&] { (void)dr::transcode_video(invalid, invalid_output, progress); });
    require(!fs::exists(invalid_output), "Failed input left an output");
    expect_error(dr::ExitCode::output, [&] {
        (void)dr::transcode_video(input, directory.path / "absent" / "out.mp4", progress);
    });
    expect_error(dr::ExitCode::output,
                 [&] { (void)dr::transcode_video(input, directory.path, progress); });
    expect_error(dr::ExitCode::output, [&] {
        (void)dr::transcode_video(input, directory.path / "unsupported.mkv", progress);
    });
    expect_error(dr::ExitCode::output, [&] { (void)dr::transcode_video(input, input, progress); });
    const auto alias = directory.path / "input alias.avi";
    fs::create_hard_link(input, alias);
    expect_error(dr::ExitCode::output, [&] { (void)dr::transcode_video(input, alias, progress); });
    verify_pair(input, alias);
    const auto blocker = directory.path / "blocker";
    std::ofstream(blocker) << "preserve me";
    expect_error(dr::ExitCode::output, [&] {
        (void)dr::transcode_video(input, blocker / "out.mp4", progress);
    });
    // Cut off encoded packets while retaining the original container's count.
    const auto truncated = directory.path / "truncated.avi";
    fs::copy_file(input, truncated);
    fs::resize_file(truncated, fs::file_size(truncated) - 1500);
    const auto truncated_output = directory.path / "truncated.mp4";
    expect_error(dr::ExitCode::processing, [&] {
        (void)dr::transcode_video(truncated, truncated_output, progress);
    });
    require(!fs::exists(truncated_output), "Truncated input published an output");
    require(read_bytes(input) == original_bytes, "Processing changed the input bytes");
    for (const auto& entry : fs::directory_iterator(directory.path)) {
        require(!entry.is_directory(), "Staging directory leaked after processing");
    }
}

void probe(const fs::path& path) {
    cv::VideoCapture capture(path.string(), cv::CAP_FFMPEG);
    require(capture.isOpened(), "Cannot open video for local probe");
    const double fps = capture.get(cv::CAP_PROP_FPS);
    const double reported = capture.get(cv::CAP_PROP_FRAME_COUNT);
    cv::Size size;
    std::uint64_t frames = 0;
    cv::Mat frame;
    while (capture.read(frame)) {
        if (frames == 0) {
            size = frame.size();
        }
        require(frame.size() == size, "Dimensions changed while probing");
        ++frames;
    }
    require(frames > 0, "No frames decoded");
    std::cout << "Backend: " << capture.getBackendName() << "; " << size.width << 'x' << size.height
              << "; fps: " << fps << "; reported frames: " << reported
              << "; decoded frames: " << frames << '\n';
}

} // namespace

int main(int argc, char* argv[]) {
    try {
        if (argc == 3 && std::string_view(argv[1]) == "--generate") {
            generate_fixture(argv[2]);
            return 0;
        }
        if (argc == 3 && std::string_view(argv[1]) == "--probe") {
            probe(argv[2]);
            return 0;
        }
        require(argc == 1, "Unknown test tool arguments");
        parser_tests();
        std::cout << "CLI parser tests passed.\n";
        video_tests();
        std::cout << "Synthetic video round trips and failure tests passed.\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "Test failure: " << error.what() << '\n';
        return 1;
    }
}
