file(MAKE_DIRECTORY "${TEST_DIR}")

function(check_cli expected pattern)
    execute_process(COMMAND "${PROGRAM}" ${ARGN}
        RESULT_VARIABLE actual OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "Expected exit ${expected}, got ${actual}: ${stdout}${stderr}")
    endif()
    if(NOT "${stdout}${stderr}" MATCHES "${pattern}")
        message(FATAL_ERROR "Expected diagnostic '${pattern}': ${stdout}${stderr}")
    endif()
endfunction()

check_cli(0 "Usage:" --help)
check_cli(2 "required")
check_cli(2 "requires" input.mov --output)
check_cli(2 "Unknown option" input.mov --unknown --output out.mp4)
check_cli(3 "regular local file" "${TEST_DIR}/missing.mov" --output "${TEST_DIR}/missing.mp4")
file(WRITE "${TEST_DIR}/invalid.mov" "Synthetic invalid video\n")
check_cli(3 "Cannot open input" "${TEST_DIR}/invalid.mov" --output "${TEST_DIR}/invalid.mp4")

execute_process(COMMAND "${FIXTURE_TOOL}" --generate "${TEST_DIR}/input with spaces.avi"
    RESULT_VARIABLE generated ERROR_VARIABLE stderr TIMEOUT 30)
if(NOT "${generated}" STREQUAL "0")
    message(FATAL_ERROR "Fixture generation failed: ${stderr}")
endif()
check_cli(4 "parent" "${TEST_DIR}/input with spaces.avi" --output "${TEST_DIR}/absent/output.mp4")
file(SHA256 "${TEST_DIR}/input with spaces.avi" fixture_before)
execute_process(COMMAND "${FIXTURE_TOOL}" --generate "${TEST_DIR}/input with spaces.avi"
    RESULT_VARIABLE refused ERROR_VARIABLE stderr TIMEOUT 30)
if(NOT "${refused}" STREQUAL "1" OR NOT "${stderr}" MATCHES "already exists")
    message(FATAL_ERROR "Fixture generator did not refuse an existing destination: ${refused}: ${stderr}")
endif()
file(SHA256 "${TEST_DIR}/input with spaces.avi" fixture_after)
if(NOT "${fixture_before}" STREQUAL "${fixture_after}")
    message(FATAL_ERROR "Fixture generator changed an existing video")
endif()
check_cli(4 "Unsupported output" "${TEST_DIR}/input with spaces.avi" --output "${TEST_DIR}/output.mkv")
file(REMOVE "${TEST_DIR}/round trip.mp4")
check_cli(0 "Verified 12 frames" "${TEST_DIR}/input with spaces.avi" --output "${TEST_DIR}/round trip.mp4")
check_cli(4 "already exists" "${TEST_DIR}/input with spaces.avi" --output "${TEST_DIR}/round trip.mp4")
check_cli(4 "already exists" "${TEST_DIR}/input with spaces.avi" --output "${TEST_DIR}/input with spaces.avi")

file(REMOVE "${TEST_DIR}/input with spaces.avi" "${TEST_DIR}/invalid.mov" "${TEST_DIR}/round trip.mp4")
